CREATE TABLE `poker`.`two` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `rankOne` int(2) NOT NULL,
  `rankTwo` int(2) NOT NULL,
  `suited` varchar(5) NOT NULL,
  `wins` int(11) NOT NULL,
  `games` int(11) NOT NULL,
  `highcard` int(11) NOT NULL,
  `highcardWins` int(11) NOT NULL,
  `pair` int(11) NOT NULL,
  `pairWins` int(11) NOT NULL,
  `twopair` int(11) NOT NULL,
  `twopairWins` int(11) NOT NULL,
  `threekind` int(11) NOT NULL,
  `threekindWins` int(11) NOT NULL,
  `straight` int(11) NOT NULL,
  `straightWins` int(11) NOT NULL,
  `flush` int(11) NOT NULL,
  `flushWins` int(11) NOT NULL,
  `fullhouse` int(11) NOT NULL,
  `fullhouseWins` int(11) NOT NULL,
  `fourkind` int(11) NOT NULL,
  `fourkindWins` int(11) NOT NULL,
  `straightflush` int(11) NOT NULL,
  `straightflushWins` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `poker`.`three` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `rankOne` int(2) NOT NULL,
  `rankTwo` int(2) NOT NULL,
  `suited` varchar(5) NOT NULL,
  `wins` int(11) NOT NULL,
  `games` int(11) NOT NULL,
  `highcard` int(11) NOT NULL,
  `highcardWins` int(11) NOT NULL,
  `pair` int(11) NOT NULL,
  `pairWins` int(11) NOT NULL,
  `twopair` int(11) NOT NULL,
  `twopairWins` int(11) NOT NULL,
  `threekind` int(11) NOT NULL,
  `threekindWins` int(11) NOT NULL,
  `straight` int(11) NOT NULL,
  `straightWins` int(11) NOT NULL,
  `flush` int(11) NOT NULL,
  `flushWins` int(11) NOT NULL,
  `fullhouse` int(11) NOT NULL,
  `fullhouseWins` int(11) NOT NULL,
  `fourkind` int(11) NOT NULL,
  `fourkindWins` int(11) NOT NULL,
  `straightflush` int(11) NOT NULL,
  `straightflushWins` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `poker`.`four` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `rankOne` int(2) NOT NULL,
  `rankTwo` int(2) NOT NULL,
  `suited` varchar(5) NOT NULL,
  `wins` int(11) NOT NULL,
  `games` int(11) NOT NULL,
  `highcard` int(11) NOT NULL,
  `highcardWins` int(11) NOT NULL,
  `pair` int(11) NOT NULL,
  `pairWins` int(11) NOT NULL,
  `twopair` int(11) NOT NULL,
  `twopairWins` int(11) NOT NULL,
  `threekind` int(11) NOT NULL,
  `threekindWins` int(11) NOT NULL,
  `straight` int(11) NOT NULL,
  `straightWins` int(11) NOT NULL,
  `flush` int(11) NOT NULL,
  `flushWins` int(11) NOT NULL,
  `fullhouse` int(11) NOT NULL,
  `fullhouseWins` int(11) NOT NULL,
  `fourkind` int(11) NOT NULL,
  `fourkindWins` int(11) NOT NULL,
  `straightflush` int(11) NOT NULL,
  `straightflushWins` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `poker`.`five` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `rankOne` int(2) NOT NULL,
  `rankTwo` int(2) NOT NULL,
  `suited` varchar(5) NOT NULL,
  `wins` int(11) NOT NULL,
  `games` int(11) NOT NULL,
  `highcard` int(11) NOT NULL,
  `highcardWins` int(11) NOT NULL,
  `pair` int(11) NOT NULL,
  `pairWins` int(11) NOT NULL,
  `twopair` int(11) NOT NULL,
  `twopairWins` int(11) NOT NULL,
  `threekind` int(11) NOT NULL,
  `threekindWins` int(11) NOT NULL,
  `straight` int(11) NOT NULL,
  `straightWins` int(11) NOT NULL,
  `flush` int(11) NOT NULL,
  `flushWins` int(11) NOT NULL,
  `fullhouse` int(11) NOT NULL,
  `fullhouseWins` int(11) NOT NULL,
  `fourkind` int(11) NOT NULL,
  `fourkindWins` int(11) NOT NULL,
  `straightflush` int(11) NOT NULL,
  `straightflushWins` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `poker`.`six` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `rankOne` int(2) NOT NULL,
  `rankTwo` int(2) NOT NULL,
  `suited` varchar(5) NOT NULL,
  `wins` int(11) NOT NULL,
  `games` int(11) NOT NULL,
  `highcard` int(11) NOT NULL,
  `highcardWins` int(11) NOT NULL,
  `pair` int(11) NOT NULL,
  `pairWins` int(11) NOT NULL,
  `twopair` int(11) NOT NULL,
  `twopairWins` int(11) NOT NULL,
  `threekind` int(11) NOT NULL,
  `threekindWins` int(11) NOT NULL,
  `straight` int(11) NOT NULL,
  `straightWins` int(11) NOT NULL,
  `flush` int(11) NOT NULL,
  `flushWins` int(11) NOT NULL,
  `fullhouse` int(11) NOT NULL,
  `fullhouseWins` int(11) NOT NULL,
  `fourkind` int(11) NOT NULL,
  `fourkindWins` int(11) NOT NULL,
  `straightflush` int(11) NOT NULL,
  `straightflushWins` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `poker`.`seven` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `rankOne` int(2) NOT NULL,
  `rankTwo` int(2) NOT NULL,
  `suited` varchar(5) NOT NULL,
  `wins` int(11) NOT NULL,
  `games` int(11) NOT NULL,
  `highcard` int(11) NOT NULL,
  `highcardWins` int(11) NOT NULL,
  `pair` int(11) NOT NULL,
  `pairWins` int(11) NOT NULL,
  `twopair` int(11) NOT NULL,
  `twopairWins` int(11) NOT NULL,
  `threekind` int(11) NOT NULL,
  `threekindWins` int(11) NOT NULL,
  `straight` int(11) NOT NULL,
  `straightWins` int(11) NOT NULL,
  `flush` int(11) NOT NULL,
  `flushWins` int(11) NOT NULL,
  `fullhouse` int(11) NOT NULL,
  `fullhouseWins` int(11) NOT NULL,
  `fourkind` int(11) NOT NULL,
  `fourkindWins` int(11) NOT NULL,
  `straightflush` int(11) NOT NULL,
  `straightflushWins` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `poker`.`eight` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `rankOne` int(2) NOT NULL,
  `rankTwo` int(2) NOT NULL,
  `suited` varchar(5) NOT NULL,
  `wins` int(11) NOT NULL,
  `games` int(11) NOT NULL,
  `highcard` int(11) NOT NULL,
  `highcardWins` int(11) NOT NULL,
  `pair` int(11) NOT NULL,
  `pairWins` int(11) NOT NULL,
  `twopair` int(11) NOT NULL,
  `twopairWins` int(11) NOT NULL,
  `threekind` int(11) NOT NULL,
  `threekindWins` int(11) NOT NULL,
  `straight` int(11) NOT NULL,
  `straightWins` int(11) NOT NULL,
  `flush` int(11) NOT NULL,
  `flushWins` int(11) NOT NULL,
  `fullhouse` int(11) NOT NULL,
  `fullhouseWins` int(11) NOT NULL,
  `fourkind` int(11) NOT NULL,
  `fourkindWins` int(11) NOT NULL,
  `straightflush` int(11) NOT NULL,
  `straightflushWins` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `poker`.`nine` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `rankOne` int(2) NOT NULL,
  `rankTwo` int(2) NOT NULL,
  `suited` varchar(5) NOT NULL,
  `wins` int(11) NOT NULL,
  `games` int(11) NOT NULL,
  `highcard` int(11) NOT NULL,
  `highcardWins` int(11) NOT NULL,
  `pair` int(11) NOT NULL,
  `pairWins` int(11) NOT NULL,
  `twopair` int(11) NOT NULL,
  `twopairWins` int(11) NOT NULL,
  `threekind` int(11) NOT NULL,
  `threekindWins` int(11) NOT NULL,
  `straight` int(11) NOT NULL,
  `straightWins` int(11) NOT NULL,
  `flush` int(11) NOT NULL,
  `flushWins` int(11) NOT NULL,
  `fullhouse` int(11) NOT NULL,
  `fullhouseWins` int(11) NOT NULL,
  `fourkind` int(11) NOT NULL,
  `fourkindWins` int(11) NOT NULL,
  `straightflush` int(11) NOT NULL,
  `straightflushWins` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `poker`.`ten` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `rankOne` int(2) NOT NULL,
  `rankTwo` int(2) NOT NULL,
  `suited` varchar(5) NOT NULL,
  `wins` int(11) NOT NULL,
  `games` int(11) NOT NULL,
  `highcard` int(11) NOT NULL,
  `highcardWins` int(11) NOT NULL,
  `pair` int(11) NOT NULL,
  `pairWins` int(11) NOT NULL,
  `twopair` int(11) NOT NULL,
  `twopairWins` int(11) NOT NULL,
  `threekind` int(11) NOT NULL,
  `threekindWins` int(11) NOT NULL,
  `straight` int(11) NOT NULL,
  `straightWins` int(11) NOT NULL,
  `flush` int(11) NOT NULL,
  `flushWins` int(11) NOT NULL,
  `fullhouse` int(11) NOT NULL,
  `fullhouseWins` int(11) NOT NULL,
  `fourkind` int(11) NOT NULL,
  `fourkindWins` int(11) NOT NULL,
  `straightflush` int(11) NOT NULL,
  `straightflushWins` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `poker`.`eleven` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `rankOne` int(2) NOT NULL,
  `rankTwo` int(2) NOT NULL,
  `suited` varchar(5) NOT NULL,
  `wins` int(11) NOT NULL,
  `games` int(11) NOT NULL,
  `highcard` int(11) NOT NULL,
  `highcardWins` int(11) NOT NULL,
  `pair` int(11) NOT NULL,
  `pairWins` int(11) NOT NULL,
  `twopair` int(11) NOT NULL,
  `twopairWins` int(11) NOT NULL,
  `threekind` int(11) NOT NULL,
  `threekindWins` int(11) NOT NULL,
  `straight` int(11) NOT NULL,
  `straightWins` int(11) NOT NULL,
  `flush` int(11) NOT NULL,
  `flushWins` int(11) NOT NULL,
  `fullhouse` int(11) NOT NULL,
  `fullhouseWins` int(11) NOT NULL,
  `fourkind` int(11) NOT NULL,
  `fourkindWins` int(11) NOT NULL,
  `straightflush` int(11) NOT NULL,
  `straightflushWins` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `poker`.`twelve` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `rankOne` int(2) NOT NULL,
  `rankTwo` int(2) NOT NULL,
  `suited` varchar(5) NOT NULL,
  `wins` int(11) NOT NULL,
  `games` int(11) NOT NULL,
  `highcard` int(11) NOT NULL,
  `highcardWins` int(11) NOT NULL,
  `pair` int(11) NOT NULL,
  `pairWins` int(11) NOT NULL,
  `twopair` int(11) NOT NULL,
  `twopairWins` int(11) NOT NULL,
  `threekind` int(11) NOT NULL,
  `threekindWins` int(11) NOT NULL,
  `straight` int(11) NOT NULL,
  `straightWins` int(11) NOT NULL,
  `flush` int(11) NOT NULL,
  `flushWins` int(11) NOT NULL,
  `fullhouse` int(11) NOT NULL,
  `fullhouseWins` int(11) NOT NULL,
  `fourkind` int(11) NOT NULL,
  `fourkindWins` int(11) NOT NULL,
  `straightflush` int(11) NOT NULL,
  `straightflushWins` int(11) NOT NULL,
  PRIMARY KEY (`id`)
)